liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    # define your filter sets under this option
    filter_sets:
        # an example thumbnail transformation definition
        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
        thumb_medium:
            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
            # setup the filter steps to apply for this transformation
            filters:
                # auto rotate the image using EXIF metadata
                auto_rotate: ~
                # strip the image of all metadata
                strip: ~
                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [530, 350]
                    mode:          outbound
                    allow_upscale: true

        thumb_intervenant:
            # set your image quality defaults
            jpeg_quality:          90
            png_compression_level: 8
            # setup the filter steps to apply for this transformation
            filters:
                # auto rotate the image using EXIF metadata
                auto_rotate: ~
                # strip the image of all metadata
                strip: ~
                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [370, 450]
                    mode:          outbound
                    allow_upscale: true
        thumb:
            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
            # setup the filter steps to apply for this transformation
            filters:
                # auto rotate the image using EXIF metadata
                auto_rotate: ~
                # strip the image of all metadata
                strip: ~
                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [350, 180]
                    mode:          outbound
                    allow_upscale: true
        thumb_small:
            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
            # setup the filter steps to apply for this transformation
            filters:
                # auto rotate the image using EXIF metadata
                auto_rotate: ~
                # strip the image of all metadata
                strip: ~
                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [159, 106]
                    mode:          outbound
                    allow_upscale: true
        thumb_back_small_128:
            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
            # setup the filter steps to apply for this transformation
            filters:
                # auto rotate the image using EXIF metadata
                auto_rotate: ~
                # strip the image of all metadata
                strip: ~
                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [128, 128]
                    mode:          outbound
                    allow_upscale: true
        thumb_back_small_400x270:
            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
            # setup the filter steps to apply for this transformation
            filters:
                # auto rotate the image using EXIF metadata
                auto_rotate: ~
                # strip the image of all metadata
                strip: ~
                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [400, 270]
                    mode:          outbound
                    allow_upscale: true

        thumb_back_small_253x145:
            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
            # setup the filter steps to apply for this transformation
            filters:
                # auto rotate the image using EXIF metadata
                auto_rotate: ~
                # strip the image of all metadata
                strip: ~
                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [253, 145]
                    mode:          outbound
                    allow_upscale: true
        thumb_back_small_300x200:
            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
            # setup the filter steps to apply for this transformation
            filters:
                # auto rotate the image using EXIF metadata
                auto_rotate: ~
                # strip the image of all metadata
                strip: ~
                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [300, 200]
                    mode:          outbound
                    allow_upscale: true

        thumb_back_small_100x50:
            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
            # setup the filter steps to apply for this transformation
            filters:
                # auto rotate the image using EXIF metadata
                auto_rotate: ~
                # strip the image of all metadata
                strip: ~
                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [100, 50]
                    mode:          outbound
                    allow_upscale: true

        thumb_blog_500x280:
            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
            # setup the filter steps to apply for this transformation
            filters:
                # auto rotate the image using EXIF metadata
                auto_rotate: ~
                # strip the image of all metadata
                strip: ~
                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [500, 280]
                    mode:          outbound
                    allow_upscale: true

        thumb_blog_730x430:
            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
            # setup the filter steps to apply for this transformation
            filters:
                # auto rotate the image using EXIF metadata
                auto_rotate: ~
                # strip the image of all metadata
                strip: ~
                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [730, 430]
                    mode:          outbound
                    allow_upscale: true
        thumb_auto:
            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
            # setup the filter steps to apply for this transformation
            filters:
                relative_resize:
                    widen: 620
        thumb_550_350:
            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
            # setup the filter steps to apply for this transformation
            filters:
                # auto rotate the image using EXIF metadata
                auto_rotate: ~
                # strip the image of all metadata
                strip: ~
                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [550, 350]
                    mode:          outbound
                    allow_upscale: true
        thumb_1920_1080:
            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
            # setup the filter steps to apply for this transformation
            filters:
                # auto rotate the image using EXIF metadata
                auto_rotate: ~
                # strip the image of all metadata
                strip: ~
                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [1920, 1080]
                    mode:          outbound
                    allow_upscale: true
        thumb_relative_resize:
            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
            # setup the filter steps to apply for this transformation
            filters:
                relative_resize:
                    widen: 750

        thumb_205_136:
            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
            # setup the filter steps to apply for this transformation
            filters:
                # auto rotate the image using EXIF metadata
                auto_rotate: ~
                # strip the image of all metadata
                strip: ~
                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [205, 136]
                    mode:          outbound
                    allow_upscale: true

        thumb_280_280:
            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
            # setup the filter steps to apply for this transformation
            filters:
                # auto rotate the image using EXIF metadata
                auto_rotate: ~
                # strip the image of all metadata
                strip: ~
                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [280, 280]
                    mode:          outbound
                    allow_upscale: true