# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: '%env(APP_LOCAL)%'
    secure_channel: '%env(SECURE_CHANNEL)%'
    gallery_directory: '%kernel.project_dir%/public/uploads/gallery'
    docfile_directory: '%kernel.project_dir%/public/uploads/docs'
    compagny: 'TIMITE & SONS'
    facebook: '#'
    google: '#'
    twitter: '#'
    linkedin: '#'
    address: '#'
    phonenumber: '+225 00 00 00 00'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\EventListener\Doctrine\HashPasswordListener:
        tags:
            - { name: doctrine.event_subscriber }

    App\EventListener\Kernel\RedirectUserListener:
        arguments: ['@security.authorization_checker', '@router']
        tags:
            - { name: kernel.event_subscriber }

    App\EventListener\Security\LoginListener:
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }

    App\Service\DraftGenerator:
        arguments: ['@doctrine.orm.entity_manager']

